if(NOT BUILD_GAME_LIBRARIES AND NOT BUILD_GAME_QVMS)
    return()
endif()

set(CGAME_SOURCES_BASEGAME ${CGAME_SOURCES} ${GAME_MODULE_SHARED_SOURCES})
set(GAME_SOURCES_BASEGAME ${GAME_SOURCES} ${GAME_MODULE_SHARED_SOURCES})
set(UI_SOURCES_BASEGAME ${UI_SOURCES} ${GAME_MODULE_SHARED_SOURCES})

if(BUILD_GAME_LIBRARIES)
    set(CGAME_MODULE_BINARY_BASEGAME "${CGAME_MODULE}${ARCH}_${BASEGAME}")
    set(GAME_MODULE_BINARY_BASEGAME "${GAME_MODULE}${ARCH}_${BASEGAME}")
    set(UI_MODULE_BINARY_BASEGAME "${UI_MODULE}${ARCH}_${BASEGAME}")

    add_library(${CGAME_MODULE_BINARY_BASEGAME} SHARED ${CGAME_SOURCES_BASEGAME} ${CGAME_BINARY_SOURCES})
    target_compile_definitions(${CGAME_MODULE_BINARY_BASEGAME} PRIVATE CGAME)
    set_target_properties(${CGAME_MODULE_BINARY_BASEGAME} PROPERTIES OUTPUT_NAME "${CGAME_MODULE_BINARY}")
    set_output_dirs(${CGAME_MODULE_BINARY_BASEGAME} SUBDIRECTORY ${BASEGAME})

    add_library(${GAME_MODULE_BINARY_BASEGAME} SHARED ${GAME_SOURCES_BASEGAME} ${GAME_BINARY_SOURCES})
    target_compile_definitions(${GAME_MODULE_BINARY_BASEGAME} PRIVATE QAGAME)
    set_target_properties(${GAME_MODULE_BINARY_BASEGAME} PROPERTIES OUTPUT_NAME "${GAME_MODULE_BINARY}")
    set_output_dirs(${GAME_MODULE_BINARY_BASEGAME} SUBDIRECTORY ${BASEGAME})

    add_library(${UI_MODULE_BINARY_BASEGAME} SHARED ${UI_SOURCES_BASEGAME} ${UI_BINARY_SOURCES})
    target_compile_definitions(${UI_MODULE_BINARY_BASEGAME} PRIVATE UI)
    set_target_properties(${UI_MODULE_BINARY_BASEGAME} PROPERTIES OUTPUT_NAME "${UI_MODULE_BINARY}")
    set_output_dirs(${UI_MODULE_BINARY_BASEGAME} SUBDIRECTORY ${BASEGAME})
endif()

if(BUILD_GAME_QVMS)
    set(CGAME_MODULE_QVM_BASEGAME "${CGAME_MODULE}qvm_${BASEGAME}")
    set(GAME_MODULE_QVM_BASEGAME "${GAME_MODULE}qvm_${BASEGAME}")
    set(UI_MODULE_QVM_BASEGAME "${UI_MODULE}qvm_${BASEGAME}")

    add_qvm(${CGAME_MODULE_QVM_BASEGAME}
        DEFINITIONS CGAME
        OUTPUT_NAME "${CGAME_MODULE}"
        OUTPUT_DIRECTORY "${BASEGAME}/vm"
        SOURCES ${CGAME_SOURCES_BASEGAME} ${CGAME_QVM_SOURCES})

    add_qvm(${GAME_MODULE_QVM_BASEGAME}
        DEFINITIONS QAGAME
        OUTPUT_NAME "${GAME_MODULE}"
        OUTPUT_DIRECTORY "${BASEGAME}/vm"
        SOURCES ${GAME_SOURCES_BASEGAME} ${GAME_QVM_SOURCES})

    add_qvm(${UI_MODULE_QVM_BASEGAME}
        DEFINITIONS UI
        OUTPUT_NAME "${UI_MODULE}"
        OUTPUT_DIRECTORY "${BASEGAME}/vm"
        SOURCES ${UI_SOURCES_BASEGAME} ${UI_QVM_SOURCES})
endif()
