name: Build
on: [push, pull_request]

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libsdl2-dev
    - name: Compile
      run: |
        cmake -S . -B build -G Ninja
        cmake --build build
  windows-msvc:
    name: Windows MSVC
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4
    - name: Compile
      run: |
        cmake -S . -B build -G "Visual Studio 17 2022"
        cmake --build build
  windows-mingw:
    name: Windows MinGW
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4
    - name: Compile
      run: |
        cmake -S . -B build -G "Ninja"
        cmake --build build
  macos:
    name: macOS
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4
    - name: Compile
      run: |
        cmake -S . -B build -G "Ninja"
        cmake --build build
